server:
  port:
    8080
spring:
  application:
    name: quiz-gateway
    gateway:
      default-filters:
      - PrefixPath=/
      routes:
      - id: flashcard
        uri: lb://flashcard
        predicates:
        - Path=/flashcard/**
      - id: quiz
        uri: lb://quiz
        predicates:
        - Path=/quiz/**
