server:
  port:
    8086
spring:
  application:
    name: 
      quiz

# Database Credentials
  datasource:
    url: jdbc:h2:mem:memdb
    username: sa
    password: password
  h2:
    console:
      enabled: true

# JPA Settings
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
